// merge_profile_i18n.js
// Fusionne les nouvelles clés "profile" dans les fichiers messages/*.json existants
// Usage : node merge_profile_i18n.js   (à lancer depuis la racine du projet)

const fs = require('fs');
const path = require('path');

const additions = {
fr: {changeCover:"📷 Changer la couverture",changeLabel:"Changer",uploading:"Upload...",offeredSkillsTitle:"Compétences Offertes",requestedSkillsTitle:"Compétences Recherchées",noSkillsOffered:"Aucune compétence listée",noSkillsRequested:"Aucune demande listée",notSpecified:"Non spécifiée",recentExchanges:"Échanges Récents",noExchangesYet:"Aucun échange pour le moment.",dangerZone:"Zone de danger",accountManagement:"Gestion du compte",accountManagementDesc:"Désactivez temporairement ou supprimez définitivement votre compte.",currentBalance:"Solde Actuel",creditsDesc:"Crédits négociables pour vos services.",transactionHistory:"Historique des transactions",noTransactions:"Aucune transaction enregistrée.",debit:"Débit",credit:"Crédit",receivedRequests:"Demandes reçues",accept:"Accepter",refuse:"Refuser",myConnectionsTitle:"Mes connexions",noConnectionsYet:"Vous n'avez pas encore de connexions.",conversationsTitle:"Conversations",lastMessagePlaceholder:"Dernier message...",writeMessagePlaceholder:"Écrivez votre message...",selectConversation:"Sélectionnez une conversation pour commencer à discuter.",connectBtn:"Se connecter",cancelRequest:"Annuler la demande",connectedLabel:"Connecté",deactivateTitle:"Désactiver votre compte ?",deactivateDesc:"Votre profil ne sera plus visible. Vous pourrez le réactiver à tout moment en vous reconnectant.",deleteAccountTitle:"Suppression définitive",irreversibleText:"irréversible",deleteAccountDescPrefix:"Cette action est ",deleteAccountDescSuffix:". Toutes vos données seront supprimées.",profileUpdatedMsg:"Profil mis à jour avec succès !",avatarUpdatedMsg:"Photo de profil mise à jour !",bioPlaceholder:"Parlez-nous de vous...",availabilityPlaceholder:"Ex: Soirs et weekends...",saveProfileChanges:"Sauvegarder les modifications",deactivateBtn:"Désactiver"},

en: {changeCover:"📷 Change cover",changeLabel:"Change",uploading:"Uploading...",offeredSkillsTitle:"Offered Skills",requestedSkillsTitle:"Requested Skills",noSkillsOffered:"No skills listed",noSkillsRequested:"No requests listed",notSpecified:"Not specified",recentExchanges:"Recent Exchanges",noExchangesYet:"No exchanges yet.",dangerZone:"Danger Zone",accountManagement:"Account management",accountManagementDesc:"Temporarily deactivate or permanently delete your account.",currentBalance:"Current Balance",creditsDesc:"Negotiable credits for your services.",transactionHistory:"Transaction history",noTransactions:"No transactions recorded.",debit:"Debit",credit:"Credit",receivedRequests:"Received requests",accept:"Accept",refuse:"Decline",myConnectionsTitle:"My connections",noConnectionsYet:"You don't have any connections yet.",conversationsTitle:"Conversations",lastMessagePlaceholder:"Last message...",writeMessagePlaceholder:"Write your message...",selectConversation:"Select a conversation to start chatting.",connectBtn:"Connect",cancelRequest:"Cancel request",connectedLabel:"Connected",deactivateTitle:"Deactivate your account?",deactivateDesc:"Your profile will no longer be visible. You can reactivate it anytime by logging back in.",deleteAccountTitle:"Permanent deletion",irreversibleText:"irreversible",deleteAccountDescPrefix:"This action is ",deleteAccountDescSuffix:". All your data will be deleted.",profileUpdatedMsg:"Profile updated successfully!",avatarUpdatedMsg:"Profile picture updated!",bioPlaceholder:"Tell us about yourself...",availabilityPlaceholder:"E.g.: Evenings and weekends...",saveProfileChanges:"Save changes",deactivateBtn:"Deactivate"},

ht: {changeCover:"📷 Chanje kouvèti",changeLabel:"Chanje",uploading:"Telechaje...",offeredSkillsTitle:"Konpetans Mwen Ofri",requestedSkillsTitle:"Konpetans Mwen Chèche",noSkillsOffered:"Pa gen konpetans ki lis",noSkillsRequested:"Pa gen demann ki lis",notSpecified:"Pa presize",recentExchanges:"Echanj Resan",noExchangesYet:"Pa gen echanj pou kounye a.",dangerZone:"Zòn danje",accountManagement:"Jesyon kont",accountManagementDesc:"Dezaktive tanporèman oswa efase kont ou nèt.",currentBalance:"Balans Aktyèl",creditsDesc:"Kredi negosyab pou sèvis ou yo.",transactionHistory:"Istwa tranzaksyon",noTransactions:"Pa gen tranzaksyon ki enrejistre.",debit:"Debi",credit:"Kredi",receivedRequests:"Demann resevwa",accept:"Aksepte",refuse:"Refize",myConnectionsTitle:"Koneksyon mwen yo",noConnectionsYet:"Ou pa gen koneksyon ankò.",conversationsTitle:"Konvèsasyon",lastMessagePlaceholder:"Dènye mesaj...",writeMessagePlaceholder:"Ekri mesaj ou...",selectConversation:"Chwazi yon konvèsasyon pou kòmanse pale.",connectBtn:"Konekte",cancelRequest:"Anile demann",connectedLabel:"Konekte",deactivateTitle:"Dezaktive kont ou?",deactivateDesc:"Pwofil ou pap vizib ankò. Ou ka reaktive li nenpòt lè lè ou rekonekte.",deleteAccountTitle:"Efasman pèmanan",irreversibleText:"irevèsib",deleteAccountDescPrefix:"Aksyon sa a ",deleteAccountDescSuffix:". Tout done ou yo ap efase.",profileUpdatedMsg:"Pwofil mete ajou avèk siksè!",avatarUpdatedMsg:"Foto pwofil mete ajou!",bioPlaceholder:"Pale nou de ou...",availabilityPlaceholder:"Egz: Aswè ak wikenn...",saveProfileChanges:"Anrejistre chanjman yo",deactivateBtn:"Dezaktive"},

es: {changeCover:"📷 Cambiar portada",changeLabel:"Cambiar",uploading:"Subiendo...",offeredSkillsTitle:"Habilidades Ofrecidas",requestedSkillsTitle:"Habilidades Buscadas",noSkillsOffered:"Ninguna habilidad indicada",noSkillsRequested:"Ninguna solicitud indicada",notSpecified:"No especificada",recentExchanges:"Intercambios Recientes",noExchangesYet:"Aún no hay intercambios.",dangerZone:"Zona de peligro",accountManagement:"Gestión de la cuenta",accountManagementDesc:"Desactiva temporalmente o elimina permanentemente tu cuenta.",currentBalance:"Saldo Actual",creditsDesc:"Créditos negociables para tus servicios.",transactionHistory:"Historial de transacciones",noTransactions:"No hay transacciones registradas.",debit:"Débito",credit:"Crédito",receivedRequests:"Solicitudes recibidas",accept:"Aceptar",refuse:"Rechazar",myConnectionsTitle:"Mis conexiones",noConnectionsYet:"Aún no tienes conexiones.",conversationsTitle:"Conversaciones",lastMessagePlaceholder:"Último mensaje...",writeMessagePlaceholder:"Escribe tu mensaje...",selectConversation:"Selecciona una conversación para empezar a chatear.",connectBtn:"Conectar",cancelRequest:"Cancelar solicitud",connectedLabel:"Conectado",deactivateTitle:"¿Desactivar tu cuenta?",deactivateDesc:"Tu perfil ya no será visible. Puedes reactivarlo en cualquier momento volviendo a iniciar sesión.",deleteAccountTitle:"Eliminación permanente",irreversibleText:"irreversible",deleteAccountDescPrefix:"Esta acción es ",deleteAccountDescSuffix:". Todos tus datos serán eliminados.",profileUpdatedMsg:"¡Perfil actualizado con éxito!",avatarUpdatedMsg:"¡Foto de perfil actualizada!",bioPlaceholder:"Cuéntanos sobre ti...",availabilityPlaceholder:"Ej: Noches y fines de semana...",saveProfileChanges:"Guardar cambios",deactivateBtn:"Desactivar"},

ar: {changeCover:"📷 تغيير الغلاف",changeLabel:"تغيير",uploading:"جاري التحميل...",offeredSkillsTitle:"المهارات المقدمة",requestedSkillsTitle:"المهارات المطلوبة",noSkillsOffered:"لا توجد مهارات مدرجة",noSkillsRequested:"لا توجد طلبات مدرجة",notSpecified:"غير محدد",recentExchanges:"التبادلات الأخيرة",noExchangesYet:"لا توجد تبادلات حتى الآن.",dangerZone:"منطقة الخطر",accountManagement:"إدارة الحساب",accountManagementDesc:"قم بتعطيل حسابك مؤقتا أو حذفه نهائيا.",currentBalance:"الرصيد الحالي",creditsDesc:"أرصدة قابلة للتفاوض لخدماتك.",transactionHistory:"سجل المعاملات",noTransactions:"لا توجد معاملات مسجلة.",debit:"سحب",credit:"إيداع",receivedRequests:"الطلبات المستلمة",accept:"قبول",refuse:"رفض",myConnectionsTitle:"اتصالاتي",noConnectionsYet:"ليس لديك أي اتصالات حتى الآن.",conversationsTitle:"المحادثات",lastMessagePlaceholder:"آخر رسالة...",writeMessagePlaceholder:"اكتب رسالتك...",selectConversation:"اختر محادثة لبدء الدردشة.",connectBtn:"تواصل",cancelRequest:"إلغاء الطلب",connectedLabel:"متصل",deactivateTitle:"تعطيل حسابك؟",deactivateDesc:"لن يكون ملفك الشخصي مرئيا بعد الآن. يمكنك إعادة تفعيله في أي وقت بتسجيل الدخول مرة أخرى.",deleteAccountTitle:"حذف نهائي",irreversibleText:"غير قابل للإلغاء",deleteAccountDescPrefix:"هذا الإجراء ",deleteAccountDescSuffix:" سيتم حذف جميع بياناتك.",profileUpdatedMsg:"تم تحديث الملف الشخصي بنجاح!",avatarUpdatedMsg:"تم تحديث صورة الملف الشخصي!",bioPlaceholder:"أخبرنا عن نفسك...",availabilityPlaceholder:"مثال: المساء وعطلات نهاية الأسبوع...",saveProfileChanges:"حفظ التغييرات",deactivateBtn:"تعطيل"},

sw: {changeCover:"📷 Badilisha jalada",changeLabel:"Badilisha",uploading:"Inapakia...",offeredSkillsTitle:"Ujuzi Ninaotoa",requestedSkillsTitle:"Ujuzi Ninaotafuta",noSkillsOffered:"Hakuna ujuzi uliotajwa",noSkillsRequested:"Hakuna maombi yaliyotajwa",notSpecified:"Haijabainishwa",recentExchanges:"Mabadilishano ya Karibuni",noExchangesYet:"Hakuna mabadilishano bado.",dangerZone:"Eneo la hatari",accountManagement:"Usimamizi wa akaunti",accountManagementDesc:"Zima kwa muda au futa akaunti yako kabisa.",currentBalance:"Salio la Sasa",creditsDesc:"Mikopo inayoweza kujadiliwa kwa huduma zako.",transactionHistory:"Historia ya miamala",noTransactions:"Hakuna miamala iliyorekodiwa.",debit:"Madeni",credit:"Mkopo",receivedRequests:"Maombi yaliyopokelewa",accept:"Kubali",refuse:"Kataa",myConnectionsTitle:"Miunganisho yangu",noConnectionsYet:"Bado huna miunganisho.",conversationsTitle:"Mazungumzo",lastMessagePlaceholder:"Ujumbe wa mwisho...",writeMessagePlaceholder:"Andika ujumbe wako...",selectConversation:"Chagua mazungumzo kuanza kuongea.",connectBtn:"Unganisha",cancelRequest:"Ghairi ombi",connectedLabel:"Umeunganishwa",deactivateTitle:"Zima akaunti yako?",deactivateDesc:"Profaili yako haitaonekana tena. Unaweza kuiwezesha tena wakati wowote kwa kuingia tena.",deleteAccountTitle:"Ufutaji wa kudumu",irreversibleText:"usioweza kurejeshwa",deleteAccountDescPrefix:"Hatua hii ni ",deleteAccountDescSuffix:". Data yako yote itafutwa.",profileUpdatedMsg:"Profaili imesasishwa kwa mafanikio!",avatarUpdatedMsg:"Picha ya profaili imesasishwa!",bioPlaceholder:"Tueleze kukuhusu...",availabilityPlaceholder:"Mfano: Jioni na wikendi...",saveProfileChanges:"Hifadhi mabadiliko",deactivateBtn:"Zima"},

wo: {changeCover:"📷 Soppi kovertur",changeLabel:"Soppi",uploading:"Telechargement...",offeredSkillsTitle:"Xam-xam yi ma jox",requestedSkillsTitle:"Xam-xam yi ma seet",noSkillsOffered:"Amul xam-xam bu nu bind",noSkillsRequested:"Amul naan bu nu bind",notSpecified:"Wonewul",recentExchanges:"Waxtaan yu Bees",noExchangesYet:"Amul waxtaan ci kel bi.",dangerZone:"Zon danjer",accountManagement:"Jefandikoo kont",accountManagementDesc:"Tej walla efase kont bi.",currentBalance:"Solde Bii",creditsDesc:"Kredi yu men a yoon ci sa njekel yi.",transactionHistory:"Istoor waxtaan yi",noTransactions:"Amul waxtaan bu bind.",debit:"Debit",credit:"Kredi",receivedRequests:"Naan yi nu jel",accept:"Nangu",refuse:"Ban",myConnectionsTitle:"Sama koneksion yi",noConnectionsYet:"Amoo koneksion.",conversationsTitle:"Waxtaan",lastMessagePlaceholder:"Bataaxal bu mujj...",writeMessagePlaceholder:"Bind sa bataaxal...",selectConversation:"Tann waxtaan bu nga begg di lakk.",connectBtn:"Jokkoo",cancelRequest:"Ban naan",connectedLabel:"Jokkoo",deactivateTitle:"Tej sa kont?",deactivateDesc:"Sa profil du fi feen. Men nga ko jefandikoo bu nga dugg deet.",deleteAccountTitle:"Efasaat",irreversibleText:"du men a delloo",deleteAccountDescPrefix:"Jef bii dafa ",deleteAccountDescSuffix:"Sa done yepp dañu koy efase.",profileUpdatedMsg:"Profil bi soppiku na ak jamm!",avatarUpdatedMsg:"Foto profil bi soppiku na!",bioPlaceholder:"Wax nu sa bopp...",availabilityPlaceholder:"Mis: Ngoon ak wikenn...",saveProfileChanges:"Dollu coppite",deactivateBtn:"Tej"},

pt: {changeCover:"📷 Alterar capa",changeLabel:"Alterar",uploading:"Enviando...",offeredSkillsTitle:"Habilidades Oferecidas",requestedSkillsTitle:"Habilidades Procuradas",noSkillsOffered:"Nenhuma habilidade listada",noSkillsRequested:"Nenhuma solicitação listada",notSpecified:"Não especificado",recentExchanges:"Trocas Recentes",noExchangesYet:"Ainda sem trocas.",dangerZone:"Zona de perigo",accountManagement:"Gestão da conta",accountManagementDesc:"Desative temporariamente ou exclua permanentemente sua conta.",currentBalance:"Saldo Atual",creditsDesc:"Créditos negociáveis para seus serviços.",transactionHistory:"Histórico de transações",noTransactions:"Nenhuma transação registrada.",debit:"Débito",credit:"Crédito",receivedRequests:"Solicitações recebidas",accept:"Aceitar",refuse:"Recusar",myConnectionsTitle:"Minhas conexões",noConnectionsYet:"Você ainda não tem conexões.",conversationsTitle:"Conversas",lastMessagePlaceholder:"Última mensagem...",writeMessagePlaceholder:"Escreva sua mensagem...",selectConversation:"Selecione uma conversa para começar a conversar.",connectBtn:"Conectar",cancelRequest:"Cancelar solicitação",connectedLabel:"Conectado",deactivateTitle:"Desativar sua conta?",deactivateDesc:"Seu perfil não será mais visível. Você pode reativá-lo a qualquer momento ao entrar novamente.",deleteAccountTitle:"Exclusão permanente",irreversibleText:"irreversível",deleteAccountDescPrefix:"Esta ação é ",deleteAccountDescSuffix:". Todos os seus dados serão excluídos.",profileUpdatedMsg:"Perfil atualizado com sucesso!",avatarUpdatedMsg:"Foto de perfil atualizada!",bioPlaceholder:"Conte-nos sobre você...",availabilityPlaceholder:"Ex: Noites e fins de semana...",saveProfileChanges:"Salvar alterações",deactivateBtn:"Desativar"},

de: {changeCover:"📷 Titelbild ändern",changeLabel:"Ändern",uploading:"Wird hochgeladen...",offeredSkillsTitle:"Angebotene Fähigkeiten",requestedSkillsTitle:"Gesuchte Fähigkeiten",noSkillsOffered:"Keine Fähigkeiten angegeben",noSkillsRequested:"Keine Anfragen angegeben",notSpecified:"Nicht angegeben",recentExchanges:"Letzte Tauschvorgänge",noExchangesYet:"Noch keine Tauschvorgänge.",dangerZone:"Gefahrenzone",accountManagement:"Kontoverwaltung",accountManagementDesc:"Deaktivieren Sie Ihr Konto vorübergehend oder löschen Sie es dauerhaft.",currentBalance:"Aktueller Saldo",creditsDesc:"Verhandelbare Guthaben für Ihre Dienste.",transactionHistory:"Transaktionsverlauf",noTransactions:"Keine Transaktionen erfasst.",debit:"Lastschrift",credit:"Gutschrift",receivedRequests:"Erhaltene Anfragen",accept:"Annehmen",refuse:"Ablehnen",myConnectionsTitle:"Meine Verbindungen",noConnectionsYet:"Sie haben noch keine Verbindungen.",conversationsTitle:"Unterhaltungen",lastMessagePlaceholder:"Letzte Nachricht...",writeMessagePlaceholder:"Schreiben Sie Ihre Nachricht...",selectConversation:"Wählen Sie eine Unterhaltung aus, um zu chatten.",connectBtn:"Verbinden",cancelRequest:"Anfrage stornieren",connectedLabel:"Verbunden",deactivateTitle:"Konto deaktivieren?",deactivateDesc:"Ihr Profil wird nicht mehr sichtbar sein. Sie können es jederzeit reaktivieren, indem Sie sich erneut anmelden.",deleteAccountTitle:"Endgültige Löschung",irreversibleText:"unwiderruflich",deleteAccountDescPrefix:"Diese Aktion ist ",deleteAccountDescSuffix:". Alle Ihre Daten werden gelöscht.",profileUpdatedMsg:"Profil erfolgreich aktualisiert!",avatarUpdatedMsg:"Profilbild aktualisiert!",bioPlaceholder:"Erzählen Sie uns von sich...",availabilityPlaceholder:"Z.B.: Abende und Wochenenden...",saveProfileChanges:"Änderungen speichern",deactivateBtn:"Deaktivieren"},

it: {changeCover:"📷 Cambia copertina",changeLabel:"Cambia",uploading:"Caricamento...",offeredSkillsTitle:"Competenze Offerte",requestedSkillsTitle:"Competenze Richieste",noSkillsOffered:"Nessuna competenza elencata",noSkillsRequested:"Nessuna richiesta elencata",notSpecified:"Non specificato",recentExchanges:"Scambi Recenti",noExchangesYet:"Ancora nessuno scambio.",dangerZone:"Zona di pericolo",accountManagement:"Gestione account",accountManagementDesc:"Disattiva temporaneamente o elimina definitivamente il tuo account.",currentBalance:"Saldo Attuale",creditsDesc:"Crediti negoziabili per i tuoi servizi.",transactionHistory:"Cronologia transazioni",noTransactions:"Nessuna transazione registrata.",debit:"Debito",credit:"Credito",receivedRequests:"Richieste ricevute",accept:"Accetta",refuse:"Rifiuta",myConnectionsTitle:"Le mie connessioni",noConnectionsYet:"Non hai ancora connessioni.",conversationsTitle:"Conversazioni",lastMessagePlaceholder:"Ultimo messaggio...",writeMessagePlaceholder:"Scrivi il tuo messaggio...",selectConversation:"Seleziona una conversazione per iniziare a chattare.",connectBtn:"Connetti",cancelRequest:"Annulla richiesta",connectedLabel:"Connesso",deactivateTitle:"Disattivare il tuo account?",deactivateDesc:"Il tuo profilo non sarà più visibile. Potrai riattivarlo in qualsiasi momento effettuando di nuovo l'accesso.",deleteAccountTitle:"Eliminazione permanente",irreversibleText:"irreversibile",deleteAccountDescPrefix:"Questa azione è ",deleteAccountDescSuffix:". Tutti i tuoi dati verranno eliminati.",profileUpdatedMsg:"Profilo aggiornato con successo!",avatarUpdatedMsg:"Foto profilo aggiornata!",bioPlaceholder:"Parlaci di te...",availabilityPlaceholder:"Es: Sere e weekend...",saveProfileChanges:"Salva modifiche",deactivateBtn:"Disattiva"},

zh: {changeCover:"📷 更换封面",changeLabel:"更换",uploading:"上传中...",offeredSkillsTitle:"提供的技能",requestedSkillsTitle:"寻求的技能",noSkillsOffered:"未列出技能",noSkillsRequested:"未列出请求",notSpecified:"未指定",recentExchanges:"最近的交流",noExchangesYet:"暂无交流。",dangerZone:"危险区域",accountManagement:"账户管理",accountManagementDesc:"暂时停用或永久删除您的账户。",currentBalance:"当前余额",creditsDesc:"可协商的服务积分。",transactionHistory:"交易历史",noTransactions:"未记录任何交易。",debit:"支出",credit:"收入",receivedRequests:"收到的请求",accept:"接受",refuse:"拒绝",myConnectionsTitle:"我的联系人",noConnectionsYet:"您还没有任何联系人。",conversationsTitle:"对话",lastMessagePlaceholder:"最新消息...",writeMessagePlaceholder:"输入您的消息...",selectConversation:"选择一个对话开始聊天。",connectBtn:"连接",cancelRequest:"取消请求",connectedLabel:"已连接",deactivateTitle:"停用您的账户？",deactivateDesc:"您的个人资料将不再可见。您可以随时重新登录来重新激活它。",deleteAccountTitle:"永久删除",irreversibleText:"不可逆转",deleteAccountDescPrefix:"此操作是",deleteAccountDescSuffix:"。您的所有数据将被删除。",profileUpdatedMsg:"个人资料更新成功！",avatarUpdatedMsg:"头像已更新！",bioPlaceholder:"介绍一下自己...",availabilityPlaceholder:"例如：晚上和周末...",saveProfileChanges:"保存更改",deactivateBtn:"停用"},

ru: {changeCover:"📷 Изменить обложку",changeLabel:"Изменить",uploading:"Загрузка...",offeredSkillsTitle:"Предлагаемые навыки",requestedSkillsTitle:"Искомые навыки",noSkillsOffered:"Навыки не указаны",noSkillsRequested:"Запросы не указаны",notSpecified:"Не указано",recentExchanges:"Недавние обмены",noExchangesYet:"Пока нет обменов.",dangerZone:"Опасная зона",accountManagement:"Управление учетной записью",accountManagementDesc:"Временно деактивируйте или навсегда удалите свою учетную запись.",currentBalance:"Текущий баланс",creditsDesc:"Договорные кредиты за ваши услуги.",transactionHistory:"История транзакций",noTransactions:"Транзакции не зарегистрированы.",debit:"Дебет",credit:"Кредит",receivedRequests:"Полученные запросы",accept:"Принять",refuse:"Отклонить",myConnectionsTitle:"Мои контакты",noConnectionsYet:"У вас пока нет контактов.",conversationsTitle:"Беседы",lastMessagePlaceholder:"Последнее сообщение...",writeMessagePlaceholder:"Напишите ваше сообщение...",selectConversation:"Выберите беседу, чтобы начать общение.",connectBtn:"Связаться",cancelRequest:"Отменить запрос",connectedLabel:"Подключено",deactivateTitle:"Деактивировать вашу учетную запись?",deactivateDesc:"Ваш профиль больше не будет виден. Вы можете повторно активировать его в любое время, снова войдя в систему.",deleteAccountTitle:"Безвозвратное удаление",irreversibleText:"безвозвратно",deleteAccountDescPrefix:"Это действие ",deleteAccountDescSuffix:". Все ваши данные будут удалены.",profileUpdatedMsg:"Профиль успешно обновлен!",avatarUpdatedMsg:"Фото профиля обновлено!",bioPlaceholder:"Расскажите нам о себе...",availabilityPlaceholder:"Напр.: Вечера и выходные...",saveProfileChanges:"Сохранить изменения",deactivateBtn:"Деактивировать"},

ja: {changeCover:"📷 カバーを変更",changeLabel:"変更",uploading:"アップロード中...",offeredSkillsTitle:"提供スキル",requestedSkillsTitle:"希望スキル",noSkillsOffered:"スキルが登録されていません",noSkillsRequested:"リクエストが登録されていません",notSpecified:"未指定",recentExchanges:"最近の交流",noExchangesYet:"まだ交流がありません。",dangerZone:"危険ゾーン",accountManagement:"アカウント管理",accountManagementDesc:"アカウントを一時的に無効化または永久に削除します。",currentBalance:"現在の残高",creditsDesc:"サービス用の交渉可能なクレジット。",transactionHistory:"取引履歴",noTransactions:"記録された取引はありません。",debit:"デビット",credit:"クレジット",receivedRequests:"受信したリクエスト",accept:"承認",refuse:"拒否",myConnectionsTitle:"マイ コネクション",noConnectionsYet:"まだコネクションがありません。",conversationsTitle:"会話",lastMessagePlaceholder:"最後のメッセージ...",writeMessagePlaceholder:"メッセージを入力...",selectConversation:"チャットを開始するには会話を選択してください。",connectBtn:"接続",cancelRequest:"リクエストを取り消す",connectedLabel:"接続済み",deactivateTitle:"アカウントを無効化しますか？",deactivateDesc:"プロフィールは表示されなくなります。再ログインすればいつでも再有効化できます。",deleteAccountTitle:"完全削除",irreversibleText:"元に戻せません",deleteAccountDescPrefix:"この操作は",deleteAccountDescSuffix:"すべてのデータが削除されます。",profileUpdatedMsg:"プロフィールが正常に更新されました！",avatarUpdatedMsg:"プロフィール写真が更新されました！",bioPlaceholder:"自己紹介をお願いします...",availabilityPlaceholder:"例：夜と週末...",saveProfileChanges:"変更を保存",deactivateBtn:"無効化"},

ko: {changeCover:"📷 커버 변경",changeLabel:"변경",uploading:"업로드 중...",offeredSkillsTitle:"제공 기술",requestedSkillsTitle:"원하는 기술",noSkillsOffered:"등록된 기술 없음",noSkillsRequested:"등록된 요청 없음",notSpecified:"지정되지 않음",recentExchanges:"최근 교환",noExchangesYet:"아직 교환 내역이 없습니다.",dangerZone:"위험 구역",accountManagement:"계정 관리",accountManagementDesc:"계정을 일시적으로 비활성화하거나 영구적으로 삭제하세요.",currentBalance:"현재 잔액",creditsDesc:"서비스에 대한 협상 가능한 크레딧.",transactionHistory:"거래 내역",noTransactions:"기록된 거래가 없습니다.",debit:"차변",credit:"대변",receivedRequests:"받은 요청",accept:"수락",refuse:"거절",myConnectionsTitle:"내 연결",noConnectionsYet:"아직 연결이 없습니다.",conversationsTitle:"대화",lastMessagePlaceholder:"마지막 메시지...",writeMessagePlaceholder:"메시지를 입력하세요...",selectConversation:"채팅을 시작하려면 대화를 선택하세요.",connectBtn:"연결",cancelRequest:"요청 취소",connectedLabel:"연결됨",deactivateTitle:"계정을 비활성화하시겠습니까?",deactivateDesc:"프로필이 더 이상 표시되지 않습니다. 다시 로그인하면 언제든지 재활성화할 수 있습니다.",deleteAccountTitle:"영구 삭제",irreversibleText:"되돌릴 수 없음",deleteAccountDescPrefix:"이 작업은 ",deleteAccountDescSuffix:". 모든 데이터가 삭제됩니다.",profileUpdatedMsg:"프로필이 성공적으로 업데이트되었습니다!",avatarUpdatedMsg:"프로필 사진이 업데이트되었습니다!",bioPlaceholder:"자신에 대해 알려주세요...",availabilityPlaceholder:"예: 저녁과 주말...",saveProfileChanges:"변경 사항 저장",deactivateBtn:"비활성화"},

nl: {changeCover:"📷 Omslag wijzigen",changeLabel:"Wijzigen",uploading:"Uploaden...",offeredSkillsTitle:"Aangeboden Vaardigheden",requestedSkillsTitle:"Gezochte Vaardigheden",noSkillsOffered:"Geen vaardigheden vermeld",noSkillsRequested:"Geen verzoeken vermeld",notSpecified:"Niet gespecificeerd",recentExchanges:"Recente Uitwisselingen",noExchangesYet:"Nog geen uitwisselingen.",dangerZone:"Gevarenzone",accountManagement:"Accountbeheer",accountManagementDesc:"Deactiveer tijdelijk of verwijder uw account permanent.",currentBalance:"Huidig Saldo",creditsDesc:"Onderhandelbare tegoeden voor uw diensten.",transactionHistory:"Transactiegeschiedenis",noTransactions:"Geen transacties geregistreerd.",debit:"Debet",credit:"Credit",receivedRequests:"Ontvangen verzoeken",accept:"Accepteren",refuse:"Weigeren",myConnectionsTitle:"Mijn connecties",noConnectionsYet:"U heeft nog geen connecties.",conversationsTitle:"Gesprekken",lastMessagePlaceholder:"Laatste bericht...",writeMessagePlaceholder:"Schrijf uw bericht...",selectConversation:"Selecteer een gesprek om te chatten.",connectBtn:"Verbinden",cancelRequest:"Verzoek annuleren",connectedLabel:"Verbonden",deactivateTitle:"Account deactiveren?",deactivateDesc:"Uw profiel is niet meer zichtbaar. U kunt het op elk moment opnieuw activeren door opnieuw in te loggen.",deleteAccountTitle:"Permanente verwijdering",irreversibleText:"onomkeerbaar",deleteAccountDescPrefix:"Deze actie is ",deleteAccountDescSuffix:". Al uw gegevens worden verwijderd.",profileUpdatedMsg:"Profiel succesvol bijgewerkt!",avatarUpdatedMsg:"Profielfoto bijgewerkt!",bioPlaceholder:"Vertel ons over jezelf...",availabilityPlaceholder:"Bijv.: Avonden en weekends...",saveProfileChanges:"Wijzigingen opslaan",deactivateBtn:"Deactiveren"},

tr: {changeCover:"📷 Kapağı değiştir",changeLabel:"Değiştir",uploading:"Yükleniyor...",offeredSkillsTitle:"Sunulan Yetenekler",requestedSkillsTitle:"Aranan Yetenekler",noSkillsOffered:"Yetenek listelenmedi",noSkillsRequested:"Talep listelenmedi",notSpecified:"Belirtilmemiş",recentExchanges:"Son Değişimler",noExchangesYet:"Henüz değişim yok.",dangerZone:"Tehlike bölgesi",accountManagement:"Hesap yönetimi",accountManagementDesc:"Hesabınızı geçici olarak devre dışı bırakın veya kalıcı olarak silin.",currentBalance:"Mevcut Bakiye",creditsDesc:"Hizmetleriniz için pazarlığa açık krediler.",transactionHistory:"İşlem geçmişi",noTransactions:"Kayıtlı işlem yok.",debit:"Borç",credit:"Alacak",receivedRequests:"Alınan talepler",accept:"Kabul et",refuse:"Reddet",myConnectionsTitle:"Bağlantılarım",noConnectionsYet:"Henüz bağlantınız yok.",conversationsTitle:"Konuşmalar",lastMessagePlaceholder:"Son mesaj...",writeMessagePlaceholder:"Mesajınızı yazın...",selectConversation:"Sohbete başlamak için bir konuşma seçin.",connectBtn:"Bağlan",cancelRequest:"Talebi iptal et",connectedLabel:"Bağlandı",deactivateTitle:"Hesabınızı devre dışı bırakmak istiyor musunuz?",deactivateDesc:"Profiliniz artık görünmeyecek. Yeniden giriş yaparak istediğiniz zaman yeniden etkinleştirebilirsiniz.",deleteAccountTitle:"Kalıcı silme",irreversibleText:"geri alınamaz",deleteAccountDescPrefix:"Bu işlem ",deleteAccountDescSuffix:". Tüm verileriniz silinecektir.",profileUpdatedMsg:"Profil başarıyla güncellendi!",avatarUpdatedMsg:"Profil fotoğrafı güncellendi!",bioPlaceholder:"Bize kendinizden bahsedin...",availabilityPlaceholder:"Örn: Akşamlar ve hafta sonları...",saveProfileChanges:"Değişiklikleri kaydet",deactivateBtn:"Devre dışı bırak"},

hi: {changeCover:"📷 कवर बदलें",changeLabel:"बदलें",uploading:"अपलोड हो रहा है...",offeredSkillsTitle:"प्रस्तावित कौशल",requestedSkillsTitle:"अनुरोधित कौशल",noSkillsOffered:"कोई कौशल सूचीबद्ध नहीं",noSkillsRequested:"कोई अनुरोध सूचीबद्ध नहीं",notSpecified:"निर्दिष्ट नहीं",recentExchanges:"हाल के आदान-प्रदान",noExchangesYet:"अभी तक कोई आदान-प्रदान नहीं।",dangerZone:"खतरा क्षेत्र",accountManagement:"खाता प्रबंधन",accountManagementDesc:"अपना खाता अस्थायी रूप से निष्क्रिय करें या स्थायी रूप से हटाएं।",currentBalance:"वर्तमान शेष",creditsDesc:"आपकी सेवाओं के लिए परक्राम्य क्रेडिट।",transactionHistory:"लेनदेन इतिहास",noTransactions:"कोई लेनदेन दर्ज नहीं।",debit:"डेबिट",credit:"क्रेडिट",receivedRequests:"प्राप्त अनुरोध",accept:"स्वीकार करें",refuse:"अस्वीकार करें",myConnectionsTitle:"मेरे कनेक्शन",noConnectionsYet:"आपके पास अभी तक कोई कनेक्शन नहीं है।",conversationsTitle:"बातचीत",lastMessagePlaceholder:"अंतिम संदेश...",writeMessagePlaceholder:"अपना संदेश लिखें...",selectConversation:"चैट शुरू करने के लिए एक बातचीत चुनें।",connectBtn:"कनेक्ट करें",cancelRequest:"अनुरोध रद्द करें",connectedLabel:"जुड़ा हुआ",deactivateTitle:"अपना खाता निष्क्रिय करें?",deactivateDesc:"आपकी प्रोफ़ाइल अब दिखाई नहीं देगी। आप कभी भी फिर से लॉग इन करके इसे पुनः सक्रिय कर सकते हैं।",deleteAccountTitle:"स्थायी विलोपन",irreversibleText:"अपरिवर्तनीय",deleteAccountDescPrefix:"यह क्रिया ",deleteAccountDescSuffix:"आपका सारा डेटा हटा दिया जाएगा।",profileUpdatedMsg:"प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!",avatarUpdatedMsg:"प्रोफ़ाइल फ़ोटो अपडेट हुई!",bioPlaceholder:"हमें अपने बारे में बताएं...",availabilityPlaceholder:"उदा: शाम और सप्ताहांत...",saveProfileChanges:"परिवर्तन सहेजें",deactivateBtn:"निष्क्रिय करें"},
};

const messagesDir = path.join(process.cwd(), 'messages');

if (!fs.existsSync(messagesDir)) {
  console.error('❌ Dossier "messages" introuvable. Lance ce script depuis la racine du projet (P:\\...\\boursedutemps).');
  process.exit(1);
}

let count = 0;
for (const [lang, profileAdditions] of Object.entries(additions)) {
  const filePath = path.join(messagesDir, `${lang}.json`);
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  ${lang}.json introuvable, ignoré.`);
    continue;
  }
  const raw = fs.readFileSync(filePath, 'utf8');
  const json = JSON.parse(raw);
  json.profile = { ...(json.profile || {}), ...profileAdditions };
  fs.writeFileSync(filePath, JSON.stringify(json, null, 2), 'utf8');
  console.log(`✅ ${lang}.json mis à jour`);
  count++;
}

console.log(`\n${count} fichiers mis à jour avec succès.`);
