CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  first_name TEXT,
  last_name TEXT,
  department TEXT,
  gender TEXT CHECK (gender IN ('Homme', 'Femme')),
  country TEXT,
  whatsapp TEXT,
  bio TEXT,
  offered_skills TEXT[],
  requested_skills TEXT[],
  availability TEXT,
  languages TEXT[],
  avatar TEXT,
  cover_photo TEXT,
  credits INTEGER DEFAULT 0,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'moderator', 'admin')),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'deactivated', 'deleted')),
  created_at TIMESTAMP DEFAULT NOW()
);
